name: Deployment Pipeline

on: 
  push: 
    branches: [dev]
  pull_request:
    branches: [main]
    types: [opened, synchronize]      

jobs: 
  avoid_redundancy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint      
        run: npm run lint        

  testing:
    runs-on: ubuntu-22.04
    steps:   
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16      
      - name: Testing
        run: npm test

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16      
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        
  deploy:
    runs-on: ubuntu-22.04
    steps:    
      - name: Deploy to Netlify
        if: ${{ github.event_name == 'push' }}
        run: echo "Deploying to Netlify..."

