name: Deployment Pipeline

on: 
  push: 
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize]      

jobs: 
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint      
        run: npm run lint        
      - name: Testing
        run: npm test
      - name: Deploy to Netlify
        if: ${{ github.event_name == 'push' }}
        run: echo "Deploying to Netlify..."

